# Documentation: https://github.com/roots/trellis#wordpress-sites
wordpress_sites:
  thebrutesquad.net:
    site_hosts:
      - brutenet.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:masoninthesis/brutenet1.1.git
    site_install: true
    site_title: Example Site
    admin_user: admin
    admin_password: admin
    admin_email: admin@brutenet.dev
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://brutenet.dev
      wp_siteurl: http://brutenet.dev/wp
      wp_env: development
      db_name: brutenet_dev
      db_user: brutenet_dbuser
      db_password: brutenet_dbpassword
